# Generated by Django 5.2.17 on 2026-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emaillogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cross_funding_policy',
            field=models.CharField(choices=[('DEFAULT', 'Use platform setting'), ('ALLOW', 'Allow'), ('WARN', 'Warn'), ('DISALLOW', 'Disallow')], default='DEFAULT', max_length=8),
        ),
    ]
