# Generated by Django 5.2.17 on 2026-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workspace_cross_funding_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='auto_select_gmp_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
