# Generated by Django 5.2.17 on 2026-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_auto_select_gmp_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillogintoken',
            name='pending_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='emaillogintoken',
            name='purpose',
            field=models.CharField(choices=[('LEGACY', 'Legacy sign-in'), ('VERIFY', 'Verify email'), ('RESET', 'Reset password')], default='LEGACY', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
