# Generated by Django 5.2.17 on 2026-09-27 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_id', models.CharField(max_length=40)),
                ('format_version', models.CharField(max_length=40)),
                ('content_type', models.CharField(max_length=100)),
                ('object_key', models.CharField(max_length=240, unique=True)),
                ('content_sha256', models.CharField(max_length=64)),
                ('planner_version', models.CharField(max_length=40)),
                ('settings_version', models.CharField(max_length=80)),
                ('input_snapshot_hash', models.CharField(max_length=64)),
                ('plan_output_hash', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField()),
                ('planned_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='planner.planrun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
