# Generated by Django 5.2.17 on 2026-09-26 15:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_emaillogintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('pan_ciphertext', models.TextField()),
                ('pan_lookup_hash', models.CharField(max_length=64)),
                ('planning_priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'pan_lookup_hash'), name='unique_workspace_pan')],
            },
        ),
    ]
