# Generated by Django 5.2.17 on 2026-09-26 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DematAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depository', models.CharField(choices=[('CDSL', 'CDSL'), ('NSDL', 'NSDL')], max_length=4)),
                ('dp_id_ciphertext', models.TextField()),
                ('client_id_ciphertext', models.TextField()),
                ('broker', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demats', to='investors.investor')),
            ],
        ),
    ]
