# Generated by Django 5.2.17 on 2026-09-27 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_workspace_auto_select_gmp_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planner_version', models.CharField(max_length=40)),
                ('settings_version', models.CharField(max_length=80)),
                ('input_snapshot_hash', models.CharField(max_length=64)),
                ('output_hash', models.CharField(max_length=64)),
                ('input_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('BLOCKED', 'Blocked')], max_length=7)),
                ('planned_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('audit_issues', models.JSONField(default=list)),
                ('uncovered', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_runs', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('ipo_ref', models.CharField(max_length=80)),
                ('applicant_ref', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=8)),
                ('lots', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('demat_ref', models.CharField(max_length=80)),
                ('bank_ref', models.CharField(max_length=80)),
                ('upi_ref', models.CharField(max_length=80)),
                ('locked', models.BooleanField(default=False)),
                ('warnings', models.JSONField(default=list)),
                ('blocking_reasons', models.JSONField(default=list)),
                ('reasons', models.JSONField(default=list)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='planner.planrun')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('plan_run', 'position'), name='unique_plan_row_position')],
            },
        ),
    ]
