# Generated by Django 5.2.17 on 2026-09-27 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_on', models.DateField()),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='applications.application')),
            ],
            options={
                'ordering': ['-sold_on', '-recorded_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_positive_quantity'), models.CheckConstraint(condition=models.Q(('price_per_share__gt', 0)), name='sale_positive_price'), models.CheckConstraint(condition=models.Q(('charges__gte', 0)), name='sale_nonnegative_charges')],
            },
        ),
    ]
