# Generated by Django 5.2.17 on 2026-09-26 15:56

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuer_name', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, max_length=40)),
                ('issue_type', models.CharField(choices=[('MAINBOARD', 'Mainboard'), ('SME', 'SME')], max_length=9)),
                ('lower_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('upper_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('lot_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('allotment_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ALLOTMENT', 'Allotment'), ('LISTED', 'Listed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=9)),
                ('publication_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=9)),
                ('source_key', models.CharField(max_length=80)),
                ('source_record_id', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('source_observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_key', 'source_record_id'), name='unique_ipo_source_record')],
            },
        ),
    ]
