# Generated by Django 5.2.17 on 2026-09-26 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GMPObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=80)),
                ('value_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_url', models.URLField(blank=True)),
                ('source_record_id', models.CharField(blank=True, max_length=160)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmp_observations', to='ipos.ipo')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at', '-fetched_at', '-id'],
            },
        ),
    ]
