# Generated by Django 5.2.17 on 2026-09-26 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_auto_select_gmp_percent'),
        ('ipos', '0002_gmpobservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOUserDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('DEFAULT', 'Automatic'), ('APPLY', 'Apply'), ('SKIP', 'Skip')], default='DEFAULT', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_decisions', to='ipos.ipo')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_decisions', to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'ipo'), name='unique_workspace_ipo_decision')],
            },
        ),
    ]
