# Generated by Django 5.2.17 on 2026-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0003_ipouserdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipouserdecision',
            name='mode',
            field=models.CharField(choices=[('RETAIL_ONLY', 'Retail Only'), ('RETAIL_PLUS_SHNI', 'Retail + sHNI'), ('SHNI_PREFERRED', 'sHNI Preferred'), ('CUSTOM', 'Custom')], default='RETAIL_ONLY', max_length=16),
        ),
    ]
