# Generated by Django 5.2.17 on 2026-09-27 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0004_ipouserdecision_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOFieldOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=32)),
                ('value', models.TextField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipo_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_overrides', to='ipos.ipo')),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipo_overrides_resumed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resumed_at__isnull', True)), fields=('ipo', 'field_name'), name='unique_active_ipo_field_override')],
            },
        ),
    ]
