# Generated by Django 5.2.17 on 2026-09-27 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0005_ipofieldoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GMPProviderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=80, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_type', models.CharField(blank=True, max_length=120)),
                ('override_value_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('override_expires_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gmp_provider_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider_key'],
            },
        ),
    ]
