# Generated by Django 5.2.17 on 2026-09-27 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0007_gmpobservationoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('COMPANY', 'Company summary'), ('FINANCIAL', 'Financial summary'), ('RISK', 'Risk summary')], max_length=10)),
                ('source_document_id', models.CharField(max_length=160)),
                ('source_document_url', models.URLField(blank=True)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('provider_key', models.CharField(max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('draft_text', models.TextField()),
                ('review_state', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=8)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='ipos.ipo')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipo_content_versions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IPOContentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipo_content_revisions', to=settings.AUTH_USER_MODEL)),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ipos.ipocontentversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ipocontentversion',
            constraint=models.UniqueConstraint(fields=('ipo', 'content_type', 'source_document_id', 'provider_key', 'model_name'), name='unique_ipo_content_document_version'),
        ),
    ]
