# Generated by Django 5.2.17 on 2026-09-27 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0008_ipocontentversion_ipocontentrevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOSourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=80)),
                ('source_record_id', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='ipos.ipo')),
            ],
        ),
        migrations.CreateModel(
            name='IPOSourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='ipos.iposourcelink')),
            ],
            options={
                'ordering': ['-observed_at', '-fetched_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='iposourcelink',
            constraint=models.UniqueConstraint(fields=('source_key', 'source_record_id'), name='unique_ipo_feed_identity'),
        ),
        migrations.AddConstraint(
            model_name='iposourcesnapshot',
            constraint=models.UniqueConstraint(fields=('link', 'payload_hash', 'observed_at'), name='unique_ipo_feed_snapshot'),
        ),
    ]
