# Generated by Django 5.2.17 on 2026-09-27 21:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0009_iposourcelink_iposourcesnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GMPPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('freshness_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)])),
                ('conflict_threshold_percent_points', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
