# Generated by Django 5.2.17 on 2026-09-27 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0010_gmppolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iposourcelink',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iposourcelink',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iposourcelink',
            name='canonical_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iposourcelink',
            name='rights_reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
