# Generated by Django 5.2.17 on 2026-09-27 23:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0011_iposourcelink_approved_at_iposourcelink_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOFeedObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=20)),
                ('source_record_id', models.CharField(max_length=160)),
                ('source_url', models.URLField()),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-observed_at', '-fetched_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source_key', 'source_record_id', 'payload_hash', 'observed_at'), name='unique_ipo_feed_observation')],
            },
        ),
    ]
