# Generated by Django 5.2.17 on 2026-09-27 23:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0012_ipofeedobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOFeedBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=20)),
                ('source_url', models.URLField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('row_keys', models.JSONField(blank=True)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-observed_at', '-fetched_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source_key', 'payload_hash', 'observed_at'), name='unique_ipo_feed_batch')],
            },
        ),
    ]
