# Generated by Django 5.2.17 on 2026-09-28 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0013_ipofeedbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEBIFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('issuer_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=40)),
                ('document_url', models.URLField(blank=True)),
                ('filing_date', models.DateField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_state', models.CharField(default='REVIEW_REQUIRED', max_length=20)),
            ],
            options={
                'ordering': ['-filing_date', 'issuer_name'],
            },
        ),
    ]
