# Generated by Django 5.2.17 on 2026-09-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0014_sebifiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOProviderSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(blank=True, max_length=40)),
                ('last_safe_error', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
