# Generated by Django 5.2.17 on 2026-09-28 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0015_ipoprovidersyncstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOEnrichmentObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=40)),
                ('source_url', models.URLField(max_length=500)),
                ('payload_hash', models.CharField(max_length=64)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(default='OK', max_length=20)),
                ('safe_error', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-fetched_at', '-snapshot_created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source_key', 'stage', 'symbol', 'payload_hash'), name='unique_ipo_enrichment_payload')],
            },
        ),
    ]
