# Generated by Django 5.2.17 on 2026-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0016_ipoenrichmentobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipofeedobservation',
            name='snapshot_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipofeedobservation',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
