# Generated by Django 5.2.17 on 2026-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0017_ipofeedobservation_snapshot_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ipoenrichmentobservation',
            name='unique_ipo_enrichment_payload',
        ),
        migrations.AddField(
            model_name='ipoenrichmentobservation',
            name='normalizer_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='ipoenrichmentobservation',
            constraint=models.UniqueConstraint(fields=('source_key', 'stage', 'symbol', 'payload_hash', 'normalizer_version'), name='unique_ipo_enrichment_payload'),
        ),
    ]
