# Generated by Django 5.2.17 on 2026-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0018_remove_ipoenrichmentobservation_unique_ipo_enrichment_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='designated_exchange',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='ipo',
            name='listing_exchanges',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='ipo',
            name='source_market',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
