# Generated by Django 5.2.17 on 2026-09-27 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_workspace_auto_select_gmp_percent'),
        ('funding', '0007_fundingpreference'),
        ('investors', '0002_demataccount'),
        ('ipos', '0004_ipouserdecision_mode'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=8)),
                ('lots', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SUBMITTED', 'Submitted'), ('BLOCKED', 'Blocked'), ('ALLOTTED', 'Allotted'), ('NOT_ALLOTTED', 'Not allotted')], default='PLANNED', max_length=12)),
                ('planned_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('result_at', models.DateTimeField(blank=True, null=True)),
                ('expected_release_date', models.DateField(blank=True, null=True)),
                ('allotted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('shares_credited_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='investors.investor')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='funding.bankaccount')),
                ('demat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='investors.demataccount')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='ipos.ipo')),
                ('plan_row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='planner.planrow')),
                ('upi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='funding.upihandle')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-planned_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'ipo', 'applicant'), name='unique_workspace_ipo_applicant')],
            },
        ),
    ]
