# Generated by Django 5.2.17 on 2026-09-26 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_emaillogintoken'),
        ('investors', '0002_demataccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_ciphertext', models.TextField()),
                ('account_lookup_hash', models.CharField(max_length=64)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cross_funding_policy', models.CharField(choices=[('DEFAULT', 'Use workspace setting'), ('ALLOW', 'Allow'), ('WARN', 'Warn'), ('DISALLOW', 'Disallow')], default='DEFAULT', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='investors.investor')),
                ('restricted_investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restricted_banks', to='investors.investor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('ADD', 'Add Money'), ('REMOVE', 'Remove Money'), ('SET', 'Set Balance')], max_length=6)),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_changes', to='funding.bankaccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'account_lookup_hash'), name='unique_workspace_bank_account'),
        ),
    ]
