# Generated by Django 5.2.17 on 2026-09-26 15:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        ('investors', '0002_demataccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIHandle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle_ciphertext', models.TextField()),
                ('handle_lookup_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('count_limit_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount_limit_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upis', to='funding.bankaccount')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upis', to='investors.investor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('handle_lookup_hash',), name='unique_upi_handle_lookup')],
            },
        ),
    ]
