# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_recurringdebit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringDebitOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('balance_change', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='funding.balancechange')),
                ('recurring_debit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='funding.recurringdebit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recurring_debit', 'due_date'), name='unique_recurring_occurrence')],
            },
        ),
    ]
