# Generated by Django 5.2.17 on 2026-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_recurringdebitoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdebit',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
