# Generated by Django 5.2.17 on 2026-09-26 15:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_recurringdebit_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringdebit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
