# Generated by Django 5.2.17 on 2026-09-26 15:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_alter_recurringdebit_amount'),
        ('investors', '0002_demataccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_preferences', to='funding.bankaccount')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_preferences', to='investors.investor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('beneficiary', 'bank'), name='unique_beneficiary_funding_bank')],
            },
        ),
    ]
