# Generated by Django 5.2.17 on 2026-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_fundingpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='operation',
            field=models.CharField(choices=[('ADD', 'Add Money'), ('REMOVE', 'Remove Money'), ('SET', 'Set Balance'), ('ALLOTMENT', 'Allotment cost')], max_length=9),
        ),
    ]
