# Generated by Django 5.2.17 on 2026-09-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_auto_select_gmp_percent'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACTIVATED', 'Activated'), ('PLAN_GENERATED', 'Plan Generated'), ('PLAN_EDITED', 'Plan Edited'), ('EXPORT_GENERATED', 'Export Generated'), ('ALLOTMENT_RECORDED', 'Allotment Recorded'), ('PNL_COMPLETED', 'Pnl Completed')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_betaev_event_t_0fa539_idx')],
            },
        ),
    ]
